import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
export const prestadoresServicoFaqs = [
  { question: "Qual regime é melhor para prestador de serviço?", answer: "Depende do faturamento. Prestadores com faturamento acima de R$ 5.000/mês se beneficiam no Simples Nacional com Fator R (a partir de 6%) ou Lucro Presumido. Fazemos análise personalizada." },
  { question: "Como funciona o Fator R para prestadores?", answer: "O Fator R é a relação folha/faturamento dos últimos 12 meses. Se ≥ 28%, você fica no Anexo III (6%) em vez do V (15,5%). Otimizamos seu pró-labore." },
  { question: "Prestador de serviço pode ser MEI?", answer: "Depende da atividade e faturamento (limite R$ 81.000/ano). Para muitos prestadores, a ME no Simples Nacional é mais vantajosa." },
  { question: "Como emitir NFS-e corretamente?", answer: "A emissão varia por município. Automatizamos o processo para que suas notas sejam emitidas corretamente e no prazo." },
  { question: "Freelancer precisa de CNPJ?", answer: "Não é obrigatório, mas é muito recomendado. Como PF paga até 27,5% de IR. Como PJ, a partir de 6%." },
  { question: "Quais CNAEs usar para prestação de serviços?", answer: "Depende do tipo de serviço. Escolhemos os CNAEs que permitem o melhor enquadramento tributário para sua atividade específica." },
];
export function PrestadoresServicoFAQ() { return (<section className="py-16 lg:py-24 bg-[#FEF3C7]"><div className="container mx-auto px-4"><div className="max-w-3xl mx-auto"><div className="text-center mb-12"><span className="text-sm font-semibold text-[#B45309] uppercase tracking-wider">Dúvidas Frequentes</span><h2 className="text-3xl lg:text-4xl font-bold text-foreground mt-2 mb-4">Perguntas sobre contabilidade para prestadores</h2><p className="text-muted-foreground text-lg">Tire suas dúvidas</p></div><Accordion type="single" collapsible className="space-y-4">{prestadoresServicoFaqs.map((f, i) => (<AccordionItem key={i} value={`item-${i}`} className="bg-card border border-border rounded-xl px-6 data-[state=open]:border-[#D97706]/50"><AccordionTrigger className="text-left text-foreground hover:text-[#B45309] py-5">{f.question}</AccordionTrigger><AccordionContent className="text-muted-foreground pb-5">{f.answer}</AccordionContent></AccordionItem>))}</Accordion></div></div></section>); }
