import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
export const profissionaisPJFaqs = [
  { question: "Vale a pena migrar de CLT para PJ?", answer: "Na maioria dos casos com salário acima de R$ 5.000, sim. Como PJ, você pode pagar a partir de 6% de impostos vs 27,5% como CLT. Mas é preciso análise caso a caso." },
  { question: "Como funciona o pro-labore otimizado?", answer: "O pro-labore é o 'salário' do sócio. Otimizamos o valor para equilibrar INSS, Fator R e benefícios previdenciários, garantindo a menor tributação total." },
  { question: "Quais os riscos da transição CLT → PJ?", answer: "Se mal planejada, pode gerar riscos trabalhistas (vínculo empregatício) e tributários. Orientamos sobre melhores práticas para uma transição segura e legal." },
  { question: "Profissional PJ pode se aposentar?", answer: "Sim! Através do INSS via pro-labore. Planejamos a contribuição ideal para garantir aposentadoria sem pagar mais imposto do que o necessário." },
  { question: "Como funciona o Fator R para PJ?", answer: "Se a relação folha/faturamento for ≥ 28%, você fica no Anexo III (6%) em vez do V (15,5%). Otimizamos seu pro-labore para maximizar essa economia." },
  { question: "Quais benefícios perco saindo da CLT?", answer: "Principalmente FGTS, férias remuneradas e 13º. Porém, a economia tributária geralmente compensa. Fazemos uma análise comparativa completa CLT x PJ." },
];
export function ProfissionaisPJFAQ() { return (<section className="py-16 lg:py-24 bg-[#E0E7FF]"><div className="container mx-auto px-4"><div className="max-w-3xl mx-auto"><div className="text-center mb-12"><span className="text-sm font-semibold text-[#4338CA] uppercase tracking-wider">Dúvidas Frequentes</span><h2 className="text-3xl lg:text-4xl font-bold text-foreground mt-2 mb-4">Perguntas sobre contabilidade para PJ</h2><p className="text-muted-foreground text-lg">Tire suas dúvidas sobre a transição e gestão PJ</p></div><Accordion type="single" collapsible className="space-y-4">{profissionaisPJFaqs.map((f, i) => (<AccordionItem key={i} value={`item-${i}`} className="bg-card border border-border rounded-xl px-6 data-[state=open]:border-[#4F46E5]/50"><AccordionTrigger className="text-left text-foreground hover:text-[#4338CA] py-5">{f.question}</AccordionTrigger><AccordionContent className="text-muted-foreground pb-5">{f.answer}</AccordionContent></AccordionItem>))}</Accordion></div></div></section>); }
