
-- Insert 88 city pages into page_metadata for sitemap generation
INSERT INTO public.page_metadata (path, priority, changefreq, last_modified)
VALUES
  -- RMC cities (high priority)
  ('/contabilidade-em-campinas', 0.8, 'monthly', now()),
  ('/contabilidade-em-americana', 0.8, 'monthly', now()),
  ('/contabilidade-em-indaiatuba', 0.8, 'monthly', now()),
  ('/contabilidade-em-sumare', 0.8, 'monthly', now()),
  ('/contabilidade-em-hortolandia', 0.8, 'monthly', now()),
  ('/contabilidade-em-valinhos', 0.8, 'monthly', now()),
  ('/contabilidade-em-vinhedo', 0.8, 'monthly', now()),
  ('/contabilidade-em-santa-barbara-doeste', 0.8, 'monthly', now()),
  ('/contabilidade-em-paulinia', 0.8, 'monthly', now()),
  ('/contabilidade-em-jaguariuna', 0.8, 'monthly', now()),
  ('/contabilidade-em-itatiba', 0.8, 'monthly', now()),
  ('/contabilidade-em-pedreira', 0.8, 'monthly', now()),
  ('/contabilidade-em-monte-mor', 0.8, 'monthly', now()),
  ('/contabilidade-em-nova-odessa', 0.8, 'monthly', now()),
  ('/contabilidade-em-artur-nogueira', 0.8, 'monthly', now()),
  ('/contabilidade-em-cosmopolis', 0.8, 'monthly', now()),
  ('/contabilidade-em-engenheiro-coelho', 0.8, 'monthly', now()),
  ('/contabilidade-em-holambra', 0.8, 'monthly', now()),
  ('/contabilidade-em-morungaba', 0.8, 'monthly', now()),
  ('/contabilidade-em-santo-antonio-de-posse', 0.8, 'monthly', now()),
  -- SP capital + interior (medium priority)
  ('/contabilidade-em-sao-paulo', 0.7, 'monthly', now()),
  ('/contabilidade-em-guarulhos', 0.6, 'monthly', now()),
  ('/contabilidade-em-santos', 0.6, 'monthly', now()),
  ('/contabilidade-em-sao-jose-dos-campos', 0.6, 'monthly', now()),
  ('/contabilidade-em-sorocaba', 0.6, 'monthly', now()),
  ('/contabilidade-em-ribeirao-preto', 0.6, 'monthly', now()),
  ('/contabilidade-em-sao-bernardo-do-campo', 0.6, 'monthly', now()),
  ('/contabilidade-em-santo-andre', 0.6, 'monthly', now()),
  ('/contabilidade-em-osasco', 0.6, 'monthly', now()),
  ('/contabilidade-em-maua', 0.6, 'monthly', now()),
  ('/contabilidade-em-diadema', 0.6, 'monthly', now()),
  ('/contabilidade-em-barueri', 0.6, 'monthly', now()),
  ('/contabilidade-em-piracicaba', 0.6, 'monthly', now()),
  ('/contabilidade-em-limeira', 0.6, 'monthly', now()),
  ('/contabilidade-em-jundiai', 0.6, 'monthly', now()),
  ('/contabilidade-em-bauru', 0.6, 'monthly', now()),
  ('/contabilidade-em-sao-caetano-do-sul', 0.6, 'monthly', now()),
  ('/contabilidade-em-jacarei', 0.6, 'monthly', now()),
  ('/contabilidade-em-atibaia', 0.6, 'monthly', now()),
  ('/contabilidade-em-cotia', 0.6, 'monthly', now()),
  ('/contabilidade-em-embu-das-artes', 0.6, 'monthly', now()),
  ('/contabilidade-em-marilia', 0.6, 'monthly', now()),
  ('/contabilidade-em-mogi-das-cruzes', 0.6, 'monthly', now()),
  ('/contabilidade-em-sao-carlos', 0.6, 'monthly', now()),
  ('/contabilidade-em-ibitinga', 0.6, 'monthly', now()),
  ('/contabilidade-em-santana-de-parnaiba', 0.6, 'monthly', now()),
  ('/contabilidade-em-taboao-da-serra', 0.6, 'monthly', now()),
  ('/contabilidade-em-sao-jose-do-rio-preto', 0.6, 'monthly', now()),
  -- RJ
  ('/contabilidade-em-rio-de-janeiro', 0.7, 'monthly', now()),
  ('/contabilidade-em-duque-de-caxias', 0.5, 'monthly', now()),
  ('/contabilidade-em-niteroi', 0.6, 'monthly', now()),
  ('/contabilidade-em-nova-iguacu', 0.5, 'monthly', now()),
  -- MG
  ('/contabilidade-em-belo-horizonte', 0.7, 'monthly', now()),
  ('/contabilidade-em-contagem', 0.5, 'monthly', now()),
  ('/contabilidade-em-uberlandia', 0.6, 'monthly', now()),
  -- ES
  ('/contabilidade-em-vitoria', 0.5, 'monthly', now()),
  -- PR
  ('/contabilidade-em-curitiba', 0.7, 'monthly', now()),
  ('/contabilidade-em-londrina', 0.5, 'monthly', now()),
  ('/contabilidade-em-maringa', 0.5, 'monthly', now()),
  ('/contabilidade-em-pinhais', 0.5, 'monthly', now()),
  -- SC
  ('/contabilidade-em-blumenau', 0.5, 'monthly', now()),
  ('/contabilidade-em-florianopolis', 0.6, 'monthly', now()),
  -- RS
  ('/contabilidade-em-porto-alegre', 0.6, 'monthly', now()),
  -- Nordeste
  ('/contabilidade-em-salvador', 0.5, 'monthly', now()),
  ('/contabilidade-em-fortaleza', 0.5, 'monthly', now()),
  ('/contabilidade-em-recife', 0.5, 'monthly', now()),
  ('/contabilidade-em-natal', 0.5, 'monthly', now()),
  ('/contabilidade-em-joao-pessoa', 0.5, 'monthly', now()),
  ('/contabilidade-em-maceio', 0.5, 'monthly', now()),
  ('/contabilidade-em-aracaju', 0.5, 'monthly', now()),
  ('/contabilidade-em-sao-luis', 0.5, 'monthly', now()),
  ('/contabilidade-em-teresina', 0.5, 'monthly', now()),
  -- Centro-Oeste
  ('/contabilidade-em-brasilia', 0.6, 'monthly', now()),
  ('/contabilidade-em-goiania', 0.5, 'monthly', now()),
  ('/contabilidade-em-campo-grande', 0.5, 'monthly', now()),
  ('/contabilidade-em-cuiaba', 0.5, 'monthly', now()),
  -- Norte
  ('/contabilidade-em-manaus', 0.5, 'monthly', now()),
  ('/contabilidade-em-belem', 0.5, 'monthly', now())
ON CONFLICT (path) DO UPDATE SET last_modified = now(), priority = EXCLUDED.priority;
